# 파이썬 벡터 실습 

## 벡터의 덧셈

In [1]:
# 벡터 덧셈 
u = [1, 2, 3]
v = [4, 5, 6]

n = len(u)
w = []

for i in range(n):
    val = u[i] + v[i]
    w.append(val)

In [2]:
print(w)

[5, 7, 9]


In [3]:
def v_add(u, v):
    """
    벡터의 덧셈
    입력값: 더하고자하는 벡터 u, v
    출력값: 벡터 u, v의 덧셈 결과 w
    """
    n = len(u)
    w = []
    for idx in range(n):
        val = u[idx] + v[idx]
        w.append(val)
    return w 

In [4]:
u = [1, 2, 3]
v = [4, 5, 6]
v_add(u, v)

[5, 7, 9]

## 스칼라와 벡터 곱

In [5]:
u = [2, 4, 3]
a = 3 

n = len(u)
w = []

for i in range(n):
    val = a*u[i]
    w.append(val)

In [6]:
w

[6, 12, 9]

In [7]:
def scalar_v_mul(a,u):
    '''
    벡터의 스칼라 곱
    입력값: 스칼라 a, 벡터 리스트 u
    출력값: 스칼라 a와 벡터 리스트 u의 곱 결과 w
    '''
    n = len(u)
    w = []

    for i in range(0, n):
        val = a*u[i]
        w.append(val) 
        
    return w

In [8]:
u = [2, 4, 3]
a = 3
scalar_v_mul(a, u)

[6, 12, 9]

## 벡터의 곱셈 

In [9]:
def v_mul(u, v):
    """
    벡터의 원소 곱
    입력값: 원소 곱 하고자할 벡터 리스트 u,v 
    출력값: 벡터 u, v의 원소 곱 결과 w 
    """
    n = len(u)
    w = []
    for idx in range(n):
        val = u[idx] * v[idx]
        w.append(val)
    return w

In [10]:
u = [1,2,4]
v = [7,3,2]
v_mul(u,v)

[7, 6, 8]

## 벡터의 나눗셈

In [11]:
def v_div(u, v):
    """
    벡터의 원소 나눗셈
    입력값: 원소 나눗셈 하고자할 벡터 리스트 u, v
    출력값: 벡터 u, v의 원소 나눗셈 결과 w 
    """
    n = len(u)
    w = []

    for idx in range(n):
        val = u[idx] / v[idx]
        w.append(val)
    return w

In [12]:
u = [6,5,9]
v = [2,2,-3]
v_div(u,v)

[3.0, 2.5, -3.0]

# 넘파이 벡터 연산 

In [13]:
import numpy as np

## 벡터 덧셈

In [14]:
u = np.array([1, 2, 3])
v = np.array([4, 5, 6])

w = u + v

In [15]:
print(w)

[5 7 9]


## 벡터 뺄셈 

In [16]:
w = u -v
print(w)

[-3 -3 -3]


## 벡터 스칼라 곱

In [17]:
a = 3 
u = np.array([1, 2, 4])

w = a * u

In [18]:
print(w)

[ 3  6 12]


## 벡터 곱셈 

In [19]:
# 벡터 곱셈
u = np.array([1,2,4])
v = np.array([7,3,2])
w = u * v
print(w)

[7 6 8]


## 벡터 나눗셈

In [20]:
# 벡터 나눗셈
u = np.array([6,5,9])
v = np.array([2,2,-3])
w = u / v

print(w)

[ 3.   2.5 -3. ]
